apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
    spec:
      containers:
        - name: microservicio-java
          image: alexbgh/microservicio-java:latest
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: service-microservicio-java
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: microservicio-java
