name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonación de código
        uses: actions/checkout@v4

      # 1. Version in pom.xml
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "8"
          distribution: "temurin"

      # 2. Compile
      - name: Build with Maven
        run: mvn package
